from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.BACKBONE_NAME = "mbv3_small"
_C.MODEL.BACKBONE_WEIGHT = None

_C.TRAIN = CN()
_C.TRAIN.DATA_ROOT = '../data'
_C.TRAIN.INPUT_SIZE = 416
_C.TRAIN.EPOCH_SIZE = 1000
_C.TRAIN.BATCH_SIZE = 16
_C.TRAIN.ANGLE_LIST = [0]  # [0, 90, 180, 270]
_C.TRAIN.LEARNING_RATE = 1e-3
_C.TRAIN.CONTINUE = False

_C.LOSS = CN()
_C.LOSS.CLASS_WEIGHT = 1.0
_C.LOSS.OFFSET_WEIGHT = 1.0
_C.LOSS.SCALE_WEIGHT = 0.5
_C.LOSS.LANDMARK_WEIGHT = 0.5
